### ISSUE TITLE
Features that are missing 

### ISSUE THREAD

**Issue by rac14** [Prim69/Replay#6]
There are many features messing but i will only tell the important once

1st - while shooting arrow from bow or crossbow it doesn't show in replay
2nd - water bucket and lava bucket doesn't show in replay
3rd - snowballs doesn't show in replay
4th - splash potions doesn't show in replay
5th - fishing rod doesn't show in replay
6th - ender pearl doesn't show in replay

**Comment by kallyluv** [comment]
I don't think you can even comprehend how hard those are to do. Fake projectile entities and updating blocks are extremely difficult to work with. Lava and water would require immense amounts of processing because of two things: 1) You'd have to track whether or not the block was placed by the player being recorded (easiest of the two), and 2) You'd have to constantly check for that block updating as well as the flowing water/lava and any block the flowing water/lava touches.

**Comment by xKurt** [comment]
Hello,
Copying the skin might also be important too.

**Comment by kallyluv** [comment]
> Hello, Copying the skin might also be important too.

@xKurt Skins should be working just fine. Mind if I ask what PMMP version you're running? If it's 4.0 I can't help you, I'm inexperienced with the new API.

**Comment by xKurt** [comment]
nvm, thanks a lot @xJustJqy !

**Comment by kallyluv** [comment]
Anytime
